name: First exercise

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
          - name: hello
            run: echo "Hello"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
          - name: success step
            run: |
                echo "will not fail"
          - name: last step
            run:
                echo "final step!"